---
title: "Append all finded csv table: R Notebook"
author: Crésus KOUNOUDJI
output: html_notebook
---


I- LES FONCTIONS

1.1- Fonction de recherche des tabeaux csv
```{r}
find_myfiles=function(files=NULL,ext=NULL,patt=NULL,dir=NULL){
  
  if (is.null(dir)){dir<-getwd()}
  setwd(dir)
  
  #tous les dossiers dur repertoire de travail
  
  all_work_dir<-list.dirs(path = ".", full.names = TRUE, recursive = TRUE)
  print(all_work_dir)
  
  #list des chemins des fichiers recherchés
  list_path<-c()
  
  #si le nom du fichier est précisé
  if (!is.null(files)){
    
    for (file in files){
      
      ##si l'extension du fichier est donnée
      if(!is.null(ext)){
        
        file<-tools::file_path_sans_ext(file)
        files_path<-reader::find.file(paste(file,ext,sep=""),dir=dir,dirs=all_work_dir)
        
        #si un pattern est donné
        if (!is.null(patt)){
          files_path<-Filter(function(x) grepl(paste(ext,"$",sep=""), x), 
                             list.files(files_path,pattern = patt, full.names = TRUE))}
        list_path<-c(list_path,files_path)
      }
      
      ##si l'extension n'est pas donnée et que l'extension n'est pas dans le nom
      if(is.null(ext) & (tools::file_ext(file)=="")){
        print("Ajoutez l'extension au nom du fichier!!")
        print("Si le problème, persiste alors le fichier n'existe probablement pas dans ce répertoire!!")
        
      }
      ##si l'extension n'est pas donnée et que l'extension est dans le nom
      if(is.null(ext) & (tools::file_ext(file)!="")){
        
        ext<-tools::file_ext(file)
        files_path<-reader::find.file(file,dir=dir,dirs=all_work_dir)
        
        #si un pattern est donné
        if (!is.null(patt)){
          files_path<-list.files(files_path,pattern = patt, full.names = TRUE)
        }
      }
    }
    list_path<-c(list_path,files_path)
  }
  
  #si le nom du fichier n'est pas précisé
  if(is.null(files)){
    
    print("pas de nom fichier")
    ##si l'extension du fichier n'est pas donnée
    if(is.null(ext) & (!is.null(patt))){
      
      for (di in all_work_dir){
        p<-list.files(di,pattern = patt, full.names = TRUE)
        list_path<-c(list_path,p)}
    }
    
    if(is.null(ext) & (is.null(patt))){
      for (di in all_work_dir){
        p<-list.files(di, full.names = TRUE)
        list_path<-c(list_path,p)}
    }
    
    ##si l'extension du fichier est donnée
    if(!is.null(ext) & (!is.null(patt))){
      
      for (di in all_work_dir){
        p<-list.files(di,pattern = patt, full.names = TRUE)
        p<-Filter(function(x) grepl(paste(ext,"$",sep=""), x),p)
        list_path<-c(list_path,p)
      }
    }
    
    if(is.null(ext) & (is.null(patt))){
      
      for (di in all_work_dir){
        p<-list.files(di, full.names = TRUE)
        p<-Filter(function(x) grepl(paste(ext,"$",sep=""), x),p)
        list_path<-c(list_path,p)}
    }
    list_path
  }
}
```

1.2- Fonction de fusion de multiple table csv
```{r}
multMerge = function(mypath=NULL){
  
  if (is.null(mypath)){
    print("donnez une liste de chemins de tableaux ou le chemin du repertoire des tableaux")
  }
  
  if (length(mypath)==1){
    
    filenames <- list.files(path = mypath, full.names = TRUE)
    
    datalist = lapply(filenames,
                      function(x){L <- readLines(x, n = 1)
                      if (grepl(";", L)) read.csv2(x) else read.csv(x)})
    
    Reduce(function(x,y) {merge(x, y, all = TRUE)}, datalist)
    
  }
  if(length(mypath)>1){
    
    filenames<-mypath
    
    datalist = lapply(filenames,
                      function(x){L <- readLines(x, n = 1)
                      if (grepl(";", L)) read.csv2(x) else read.csv(x)})
    
    Reduce(function(x,y) {merge(x, y, all = TRUE)}, datalist)
  }
}
```

1.3- Fonction de lecture du csv en fonction du type
```{r}
rcsv_sep=function(file_path){
    L <- readLines(file_path, n = 1)
    if (grepl(";", L)) read.csv2(file_path) else read.csv(file_path)
    }
```


II- Fusion des tables de RMSE
```{r include=FALSE}
# Le chemin: par défaut le répertoire du script
directory<-getwd()

#Liste de tous les fichier csv "rmse" de tous les dossiers
all_csv_path<-find_myfiles(patt="rmse",ext=".csv",dir=directory)

#fusion des tables
df<-multMerge(file.path(all_csv_path))
df<-df[,-(dim(df)[2])]
#exportation de la table
write.csv2(df,file.path(paste("rmse_simulation_ocs",".csv",sep="")),row.names=FALSE)
```




